name=RGBA16 Tools
version=0.1
author=GlitchyPSI
maintainer=GlitchyPSI <glitchy@glitchypsi.xyz>
sentence=RGBA16 (5551) drawing helpers for the Adafruit GFX Library.
paragraph=RGBA16 (5551) drawing helpers for the Adafruit GFX Library.
category=Display
url=https://github.com/GlitchyPSIX/adafruit_rgba16_tools
architectures=*
depends=Adafruit GFX Library
